title: Middlebury Screenwriters Workshop
description: ""
baseurl: ""

apply_link: "https://filmfreeway.com/festival/MiddleburyScriptLab"

markdown: kramdown
exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - yarn.lock
  - README.md
  - "*.log"

collections:
- sections
