title: Middlebury Screenwriters Workshop
description: ""
baseurl: ""

apply_link: "#"

nav:
- text: Overview
  link: "#overview"
  class: js-spy js-link
- text: People
  link: "#people"
  class: js-spy js-link
- text: Application
  link: "#"
- text: Contact
  link: "#"

markdown: kramdown
exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - yarn.lock
  - README.md
  - "*.log"
